const request_data: any = [
    {
        key: "1",
        user_name: "John Brown",
        blood_group: "A+",
        blood_quantity: 2,
        cause: "Cancer",
        medical_name: "DMC",
        phone: "0345-1234567",
        email: "john.brown@gmail.com",
        message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, eaque ",
        address: "Dhilhi",
    },
    {
        key: "2",
        user_name: "Jim Green",
        blood_group: "B+",
        blood_quantity: 1,
        cause: "Cancer",
        medical_name: "DMC",
        phone: "0345-1234567",
        email: "jimgreen@gmail.com",
        message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, eaque ",
        address: "Lahore",
    },
    {
        key: "3",
        user_name: "Joe Black",
        blood_group: "O+",
        blood_quantity: 4,
        cause: "Covid-19",
        medical_name: "DMC",
        phone: "0345-1234567",
        email: "joe1223@gmail.com",
        message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, eaque ",
        address: "Dhaka",
    },
    {
        key: "4",
        user_name: "Jim Red",
        blood_group: "AB+",
        blood_quantity: 2,
        cause: "Cancer",
        medical_name: "DMC",
        phone: "0345-1234567",
        email: "jim321@gmail.com",
        message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, eaque ",
        address: "Karachi",
    },
    {
        key: "5",
        user_name: "Jim Blue",
        blood_group: "A+",
        blood_quantity: 1,
        cause: "Covid-19",
        medical_name: "DMC",
        phone: "0345-1234567",
        email: "bluen@gmail.com",
        message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, eaque ",
        address: "Sylhet",
    },
    {
        key: "6",
        user_name: "Joe Black",
        blood_group: "O+",
        blood_quantity: 3,
        cause: "Covid-19",
        medical_name: "DMC",
        phone: "0345-1234567",
        email: "joe1223@gmail.com",
        message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, eaque ",
        address: "Kacchi",
    },
    {
        key: "7",
        user_name: "Mongsano Marma",
        blood_group: "AB+",
        blood_quantity: 2,
        cause: "Cancer",
        medical_name: "DMC",
        phone: "0345-1234567",
        email: "jim321@gmail.com",
        message: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, eaque ",
        address: "Chittagong",
    },
];

export { request_data };

