import Head from 'next/head';
import Home from '../components/Home/Home';
import Information from '../components/Information/Information';
// import Blogs from '../components/Blogs/Blogs';
// import Image from 'next/image';
import Layout from '../components/Layouts/MainLayout';
// import { get_all_blogs, get_all_users } from '../services/blog.service';
// import styles from '../styles/Home.module.css';

export default function Main(props: any) {
  
  return (
    <div>
      <Head>
        <title>Save Lives BD</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"></link> */}
        <link rel="icon" href="/logo.png" />
      </Head>

      <Layout>
        {/* <Login/> */}
        <main>
          <Home/>
          <Information/>
        </main>

      </Layout>
    </div>
  )
};

export async function getServerSideProps(context: any) {
  // const posts = await get_all_blogs();
  // // const users = await get_all_users();
  // const KEY = '15674931-a9d714b6e9d654524df198e00&q';
  // const res = await fetch(`https://pixabay.com/api/?key=${KEY}=${""}&image_type=photo&pretty=true`);
  // const photos = await res.json();

  // console.log({photos});
  // check if user is logged in from access token and redirect to login page
  // const token = context.req.cookies.access_token;
  // const token = localStorage.getItem('access_token');
  // const user = await find_user(token);
  // if (!user) {
    
  // const token = context.req.cookies.access_token;
  // if (!token) {
  //   return {
  //     redirect: {
  //       destination: "/login",
  //       permanent: false,
  //     },
  //   };
  // }

  
  return {
    props: {
      info: 'This is main page',
    }
  }
}
